// function to handle the form submission
function submitOrder(event) {
    event.preventDefault(); // prevent default form submission
    const name = document.getElementById('name').value;
    const email = document.getElementById('email').value;
    const flavor = document.getElementById('flavor').value;
    const size = document.getElementById('size').value;
    const design = document.getElementById('design').value;
    const quantity = document.getElementById('quantity').value;

    // for demonstration, you can log the order details or alert them
    alert(`Order Details:\nName: ${name}\nEmail: ${email}\nFlavor: ${flavor}\nSize: ${size}\nDesign: ${design}\nQuantity: ${quantity}`);

    // you can also process the order here (e.g., send it to a server)
}

// function to handle cancelling the order
function cancelOrder() {
    // reset the form fields
    document.getElementById('cake-order-form').reset();
    alert('Your order has been cancelled.');
}

// adding event listeners for form submission and cancellation
window.onload = function() {
    const form = document.getElementById('cake-order-form');
    const cancelButton = document.querySelector('.form-buttons button[type="button"]');

    form.addEventListener('submit', submitOrder);
    cancelButton.addEventListener('click', cancelOrder);
}

function checkStoreHours() {
    const now = new Date();
    const currentHour = now.getHours(); // get the current hour (0-23)
    const statusElement = document.getElementById('store-status');

    // check if the store is open (7 am to 7 pm)
    if (currentHour >= 7 && currentHour < 19) {
        statusElement.textContent = "🌟 we're open! come on in!";
        statusElement.style.color = "green"; // green color for open
    } else {
        statusElement.textContent = "❌ we're closed. please visit us during our operating hours: 7 am - 7 pm.";
        statusElement.style.color = "red"; // red color for closed
    }
}

// call the function to check store hours on page load
// this script is generated by chatgpt, since we have not tackled yet about javascript
window.onload = checkStoreHours;